import * as Cesium from 'cesium';
export const MAP_STACKS = [
  {
    id: 'photoreal',
    label: 'Google 3D',
    shortLabel: '3D',
    kind: 'photoreal',
    requiresIon: false,
  },
  {
    id: 'bing-aerial',
    label: 'Bing Aerial',
    shortLabel: 'Aerial',
    kind: 'ion',
    style: Cesium.IonWorldImageryStyle.AERIAL,
    requiresIon: true,
  },
  {
    id: 'bing-labels',
    label: 'Bing Labels',
    shortLabel: 'Labels',
    kind: 'ion',
    style: Cesium.IonWorldImageryStyle.AERIAL_WITH_LABELS,
    requiresIon: true,
  },
  {
    id: 'esri-imagery',
    label: 'Esri Satellite',
    shortLabel: 'SAT',
    kind: 'esri-imagery',
    requiresIon: false,
  },
  {
    id: 'osm',
    label: 'OSM',
    shortLabel: 'OSM',
    kind: 'osm',
    requiresIon: false,
  },
  {
    id: 'carto-positron',
    label: 'CARTO Positron',
    shortLabel: 'LIGHT',
    kind: 'carto',
    style: 'light_all',
    requiresIon: false,
  },
  {
    id: 'carto-dark',
    label: 'CARTO Dark Matter',
    shortLabel: 'DARK',
    kind: 'carto',
    style: 'dark_all',
    requiresIon: false,
  },
  {
    id: 'openfreemap-dark',
    label: 'OpenFreeMap Dark',
    shortLabel: 'OFM',
    kind: 'openfreemap',
    requiresIon: false,
  },
];
